### ISSUE TITLE
HTTP Server mTLS Crash

### ISSUE THREAD

**Issue by gabe-l-hart** [caikit/caikit#477]
## Describe the bug

```
(*) Traceback (most recent call last):
(*) File "/opt/miniconda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
(*) return _run_code(code, main_globals, None,
(*) File "/opt/miniconda/lib/python3.9/runpy.py", line 87, in _run_code
(*) exec(code, run_globals)
(*) File "/opt/miniconda/lib/python3.9/site-packages/caikit/runtime/__main__.py", line 92, in <module>
(*) main()
(*) File "/opt/miniconda/lib/python3.9/site-packages/caikit/runtime/__main__.py", line 88, in main
(*) _http_server.start(blocking=True)  # make http always blocking
(*) File "/opt/miniconda/lib/python3.9/site-packages/caikit/runtime/http_server/http_server.py", line 199, in start
(*) self.server.run()
(*) File "/opt/miniconda/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
(*) return asyncio.run(self.serve(sockets=sockets))
(*) File "/opt/miniconda/lib/python3.9/asyncio/runners.py", line 44, in run
(*) return loop.run_until_complete(main)
(*) File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
(*) File "/opt/miniconda/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
(*) config.load()
(*) File "/opt/miniconda/lib/python3.9/site-packages/uvicorn/config.py", line 430, in load
(*) self.ssl: Optional[ssl.SSLContext] = create_ssl_context(
(*) File "/opt/miniconda/lib/python3.9/site-packages/uvicorn/config.py", line 124, in create_ssl_context
(*) ctx.load_verify_locations(ca_certs)
(*) OSError: [Errno 36] File name too long
```

**Comment by gabe-l-hart** [comment]
This is almost certainly an issue with when the client CA cert is passed by value rather than via a path to a string. Passing the tls CA by string is valid for the `grpc` server, so we should support this for HTTP as well.
