### ISSUE TITLE
regression? HTTP server won't start because: AttributeError: type object 'list' has no attribute 'model_json_schema'

### ISSUE THREAD

**Issue by markstur** [caikit/caikit#532]
## Describe the bug

A list in a task (run) signature like this:

@task(
    required_parameters={"source_sentence": str, "sentences": List[str]},
    output_type=FloatSequence
)

Works for gRPC, but HTTP server fails with:

> AttributeError: type object 'list' has no attribute 'model_json_schema'

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: 3.11
- Library version:  caikit==0.22.0

## Sample Code

See above.

## Expected behavior

I think this is a regression.  It used to work.  Just updated to new release.

## Observed behavior

What you see happening (error messages, stack traces, etc...)

## Additional context

Should've mentioned that I ran into this while trying the new multi-task, but I don't think that is relevant.

Added stack trace (in comment) showing where the pydantic_model.model_json_schema() is now a problem.  Looks like here: https://github.com/caikit/caikit/commit/eea690d3611182e953ea682e46398e397a33112a#diff-8c48c03bdb3588a96567eff810341f816e17768a82d89ab2a501e7d8649abc94R391

**Comment by markstur** [comment]
Traceback (most recent call last):
  File "/Users/markstur/gh/caikit-serving/demo/server/start_runtime.py", line 41, in <module>
    main()
  File "/Users/markstur/gh/caikit-serving/venv/lib/python3.11/site-packages/caikit/runtime/__main__.py", line 87, in main
    _http_server = RuntimeHTTPServer()
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/markstur/gh/caikit-serving/venv/lib/python3.11/site-packages/caikit/runtime/http_server/http_server.py", line 150, in __init__
    self._bind_routes(self.inference_service)
  File "/Users/markstur/gh/caikit-serving/venv/lib/python3.11/site-packages/caikit/runtime/http_server/http_server.py", line 276, in _bind_routes
    self._add_unary_input_unary_output_handler(rpc)
  File "/Users/markstur/gh/caikit-serving/venv/lib/python3.11/site-packages/caikit/runtime/http_server/http_server.py", line 392, in _add_unary_input_unary_output_handler
    responses=self._get_response_openapi(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markstur/gh/caikit-serving/venv/lib/python3.11/site-packages/caikit/runtime/http_server/http_server.py", line 669, in _get_response_openapi
    pydantic_model.model_json_schema()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 1287, in __getattr__
    return getattr(self.__origin__, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'list' has no attribute 'model_json_schema'

**Comment by evaline-ju** [comment]
[0.23.0](https://github.com/caikit/caikit/releases) was just released and should address this

**Comment by evaline-ju** [comment]
[0.23.0](https://github.com/caikit/caikit/releases/tag/v0.23.0) just released should address this
